# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c94dfe4db7e592a3e408973da83fe4f2663f8a1d6335cfe8b16749d9aa01d750682ecd2f55481deff9367ac8369bb434535c110d5b50b26325ccec3584a88788

test:
  secret_key_base: 4c85c838d022151b21cd17d8898defb211af815bb5f35bf247b8c3a07eb4f6c0fbb27eeaa29b66dafe063a32650acb0af3de33956f32ec62d3a213af0eba0f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
